### PR TITLE
Fixing reset of Column Structure automatically

### PR DESCRIPTION
**Pull request by stevenndungu**
@lilyclements  this is ready for you to merge.

Othws the dialogue is working fine.No issues. After merging this should be ready for  Danny

### CODE REVIEW

**Comment by lilyclements** [comment]
@stevenndungu excellent, thank you!

**Comment by stevenndungu** [comment]
@lilyclements  You are welcome.

**Comment by stevenndungu** [comment]
@dannyparsons  this is ready for you to review.

**Comment by dannyparsons** [comment]
which pull request? this is in Lily's repo

**Comment by stevenndungu** [comment]
Sorry, a mistake. I did this in a rush.. it is pull request #3119

**Pull request merged**
