### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by lilyclements**

### CODE REVIEW

**Comment by lilyclements** [comment]
@Patowhiz let me know when this is ready for merge with changes outlined

**Comment by Patowhiz** [comment]
Will do so

**Comment by Patowhiz** [comment]
@lilyclements the code changes were merged to master. And I think @Wycklife is working on dlgEnter in PR #5972.

**Comment by lilyclements** [comment]
@Patowhiz I don't follow. What would you like me to do? Close this PR or review and merge in?

**Comment by Patowhiz** [comment]
"@Patowhiz let me know when this is ready for merge with changes outlined"

@lilyclements I was replying to that request.  I guess this PR can now be closed.

**Comment by lilyclements** [comment]
Sure. I'm happy to close this PR but I don't understand why there were changes made to this branch.

**Comment by lilyclements** [comment]
Do you want me to close this, or merge this into another branch? If merge, can you outline the changes you've made here and link me to an issue on it?

**Pull request closed without merging**
